package:
  name: cadracks_core
  version: "0.1.2"

source:
  path: ../cadracks_core

build:
  number: 0
  noarch: python
  script: python setup.py install
  include_recipe: True

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - matplotlib
    - networkx
    - corelib
    - aocutils
    - aocxchange
    - ccad
    - party
    - wxpython
    # - pyqt >=5
    # - pythonocc-core ==0.18.2

about:
  home: https://github.com/cadracks/cadracks_core
  license: GPLv3
  license_file: COPYING
  summary: Modelling of complex objects